### ISSUE TITLE
Java namespace implies this is owned by commonmark.org

### ISSUE THREAD

**Issue by coding-horror** [commonmark/commonmark-java#187]
The namespace of the project implies that it is owned by `commonmark.org`, but it is owned by Atlassian:

```
import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
```

Expected behavior:

```
import com.atlassian.commonmark.node.*;
import com.atlassian.commonmark.parser.Parser;
import com.atlassian.commonmark.renderer.html.HtmlRenderer;
```

Not only is this misleading, it prevents commonmark.org from ever publishing a Java implementation under its own name. It's also important to note that Atlassian is a commercial organization while commonmark.org is not.

Also [the Java rules for package naming](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) do indicate the package should use the company domain name when publishing the Java packages:

> Companies use their reversed Internet domain name to begin their package names—for example, `com.example.mypackage` for a package named mypackage created by a programmer at `example.com`.
> 
> Name collisions that occur within a single company need to be handled by convention within that company, perhaps by including the region or the project name after the company name (for example, `com.example.region.mypackage`).

**Comment by robinst** [comment]
Hi Jeff.

I explicitly asked permission from @jgm back when I started the project, quote from his email from 13 April 2005:

> Neither Jeff Atwood nor I have any objections to your using the org.commonmark namespace for your module.

Note that back then, the https://github.com/commonmark/ organization wasn't being used yet. Now that the other repositories are there too, I would love to transfer the repository there! That has always been my long-term goal, which is also why the license is exactly the same as commonmark.js.

If this is something that you and @jgm are interested in, I can probably get permission from Atlassian. I think it would be beneficial for both commonmark and commonmark-java.

**Comment by jgm** [comment]
@coding-horror, I don't really recall this discussion, but I looked it up and Robin is right; he asked about this, I wrote to you, and you replied "I think using the namespace is fine!"

**Comment by coding-horror** [comment]
Ah, my bad, I didn't remember that conversation from 2015. @jgm should we transfer the repo to https://github.com/commonmark/

**Comment by jgm** [comment]
I'd be fine with transferring it.

**Comment by coding-horror** [comment]
ok, let's transfer away @robinst 🤗

**Comment by robinst** [comment]
Awesome! I'll ask Atlassian for permission.

**Comment by coding-horror** [comment]
Any updates on this? Appreciate the effort!

**Comment by robinst** [comment]
Yes! I've got the permission. Next week I'm planning to move the repository; I also need to work on the release process, and probably changing the Maven Central group ID.

**Comment by robinst** [comment]
@coding-horror Tried transferring, but I get this error:

> You don’t have the permission to create public repositories on commonmark

**Comment by coding-horror** [comment]
aha! My apologies. Are there any settings I need to change, can you initiate a transfer? 

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

**Comment by robinst** [comment]
From the error message, I think you need to add me as a member of the commonmark org, and make sure that members have permission to create public repositories::

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization

**Comment by coding-horror** [comment]
OK I've invited you as a team member to CommonMark, and I've set the preference (per the above) so that members can create Public repositories. Let me know if this helps / works!

**Comment by robinst** [comment]
It worked now, yay! Going to close this and open new issues for the other changes.
