### ISSUE TITLE
Is conversion of markdown with mathjax supported?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [commonmark/commonmark-java#194]
Is conversion of markdown with mathjax supported?

**Comment by robinst** [comment]
No. Can you point to other implementations that support it? I'd like to see what syntax they use and how they output it.

**Comment by Sebastian-Nielsen** [comment]
Sorry, I meant katex; anyways, I guess it is very easy to implement.  [source: stackoverflow](https://stackoverflow.com/a/56038155/7123519)

Whenever you see $$ or $$$$ in the markdown, just enclose it in a p tag (or any tag really). 

So, this: "Hello, there this is $2=3\frac{2}{\pi}$ an inline comment, $$ 3 \neq 5$$ is not inline"

Is in html: 

<p>Hello, there this is $2=3\frac{2}{\pi}$ an inline comment, $$ 3 \neq 5$$ is not inline</p>

<script>
$(document).ready(function () { // this need jquery
  renderMathInElement(document.body, {
    // ...options...
    delimiters: [
      { left: "$$", right: "$$", display: true },
      { left: "$", right: "$", display: false },
      { left: "\\[", right: "\\]", display: true }
    ]
  });
});
</script>

**Comment by robinst** [comment]
Sounds like this can be done purely in JS on the resulting HTML, so no specific support is needed within commonmark-java. Let me know if that works for you.

**Comment by crowlogic** [comment]
why not implement something with https://github.com/opencollab/jlatexmath instead of relying on code for what should be a document
