### ISSUE TITLE
Re-enable Android test build

### ISSUE THREAD

**Issue by robinst** [commonmark/commonmark-java#196]
The Android test build that used to run on Travis CI has been disabled, see 94a4606f387183c0576d29458962c8d2c0610f11

This issue is for re-enabling it. Can we run it on GitHub actions? Is there a better way to test Android compatibility?

**Comment by noties** [comment]
Hello @robinst ,

it is possible to run Android tests as junit tests and execute them with Github Actions. If no one is working on it already I can prepare a pull request

**Comment by robinst** [comment]
@noties That would be great :)! See the existing stuff in the `commonmark-android-test` folder.

**Comment by noties** [comment]
Hello @robinst ,

sorry it took a bit too much of time, but it is done in #197

**Comment by robinst** [comment]
Re-enabled now, thanks @noties!
