### ISSUE TITLE
At some point, the label '<p>' is redundant

### ISSUE THREAD

**Issue by Stone-Fly** [commonmark/commonmark-java#201]
Steps to reproduce the problem (provide example Markdown if applicable):

```
>K = 1, N = 2
>K = 2, N = 6
>K = 3, N = 14
```

Expected behavior:

```
<blockquote>
K = 1, N = 2
K = 2, N = 6
K = 3, N = 14
</blockquote>
```

Actual behavior:

```
<blockquote>
<p>K = 1, N = 2
K = 2, N = 6
K = 3, N = 14</p>
</blockquote>
```

I think it should display three lines, not one line. The same problem in picture display.

```
picture:
![avatar](http://baidu.com/pic/doge.png)
```

Expected behavior:

```
picture:
<img src="http://baidu.com/pic/doge.png" alt="avatar" />
```

Actual behavior:

```
<p>picture:
<img src="http://baidu.com/pic/doge.png" alt="avatar" /></p>
```

**Comment by robinst** [comment]
It works the same way as the reference implementation (commonmark.js), see [here](https://spec.commonmark.org/dingus/?text=%3EK%20%3D%201%2C%20N%20%3D%202%0A%3EK%20%3D%202%2C%20N%20%3D%206%0A%3EK%20%3D%203%2C%20N%20%3D%2014):

<img width="973" alt="Screen Shot 2021-02-13 at 23 06 04" src="https://user-images.githubusercontent.com/16778/107849546-14c7a780-6e50-11eb-9e0e-21aa6cd7b03d.png">

So this is not a bug.

> I think it should display three lines, not one line.

If you want newlines in the source to render as a line break, you can use this option on the HTML renderer:

```
HtmlRenderer renderer = HtmlRenderer.builder().softbreak("<br>").build();
```

Does that help?
