### ISSUE TITLE
How to strip HTML comments, Script and Style Tags

### ISSUE THREAD

**Issue by Clashsoft** [commonmark/commonmark-java#203]
Is there a way to configure the renderer to strip HTML comments (`<!-- -->`), script and style tags? The latter especially to prevent XSS. I found that using `escapeHtml(true)` can prevent that, but it also puts these blocks as well as comments into the output as text. Is there a way to get the best out of both? Perhaps this is just a bug with the way comments are handled.

## Input

```markdown
foo bar baz

<script>alert("xss")</script>
<style>body { background-color: red; }</style>
<!-- comment -->
```

[Dingus](https://spec.commonmark.org/dingus/?text=foo%20bar%20baz%0A%0A%3Cscript%3Ealert(%22xss%22)%3C%2Fscript%3E%0A%3Cstyle%3Ebody%20%7B%20background-color%3A%20red%3B%20%7D%3C%2Fstyle%3E%0A%3C!--%20comment%20--%3E)

## Output with `escapeHtml(false)`

Note the XSS!

```html
<p>foo bar baz</p>
<script>alert("xss")</script>
<style>body { background-color: red; }</style>
<!-- comment -->
```

## Output with `escapeHtml(true)`

Note how the comment is also there.

```html
<p>foo bar baz</p>

&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;
&lt;style&gt;body { background-color: red; }&lt;/style&gt;
&lt;!-- comment --&gt;
```

## Expected Output

```html
<p>foo bar baz</p>
```

## Workaround

I was able to strip these tags with a postprocessor, but there ought to be a simpler way:

```java
Visitor visitor = new AbstractVisitor() {
    @Override
    public void visit(HtmlBlock htmlBlock) {
        final String literal = htmlBlock.getLiteral();
        if (literal.startsWith("<!--") || literal.startsWith("<script") || literal.startsWith("<style")) {
            htmlBlock.setLiteral("");
        }
    }
};

Parser parser = Parser.builder().extensions(EXTENSIONS).postProcessor(node -> {
    node.accept(visitor);
    return node;
}).build();
```

**Comment by robinst** [comment]
I'm not sure it's a common enough use case to have this built in. Also, note that you could have something like this, so the current postprocessor is not enough:

```
<div><script>alert("xss")</script></div>
```

To properly sanitize the output, I would recommend something like https://owasp.org/www-project-antisamy/

**Comment by Clashsoft** [comment]
@robinst You are right, there are also other vulnerabilities with my workaround like `<img src="#" onerror="alert("xss")">`. Probably best to use some dedicated library.
