### ISSUE TITLE
"normalizeLabelContent" should not convert all content to lower case

### ISSUE THREAD

**Issue by devkanro** [commonmark/commonmark-java#204]
**Is your feature request related to a problem? Please describe.**
I am building a [protobuf language plugin](https://github.com/devkanro/intellij-protobuf-plugin) for IntelliJ platform.
And I use the `commonmark-java` for document comment rendering.
I need to resolve the references in document like `[selector][google.api.DocumentationRule.selector]`.
So I create a `DelegateInlineParserFactory` to intercept `InlineParserContext` instance.
But I found the parameter `label` of the `getLinkReferenceDefinition` method has been converted to lower case by `String label = Escaping.normalizeLabelContent(ref);` in line 326 of `InlineParserImpl.java`
The `google.api.documentationrule.selector` is not a valid symbol, so I can't resolve it to a reference link to language element.

**Describe the solution you'd like**
Maybe the case ignoring should not handle in `InlineParserImpl`, it should pass the original label value to `InlineParserContext`, let `InlineParserContext` decide whether to ignore case.

**Comment by robinst** [comment]
Yeah I think that makes sense, I’ll have a look next week.

**Comment by robinst** [comment]
Raised a PR for this change, have a look: https://github.com/commonmark/commonmark-java/pull/205

**Comment by devkanro** [comment]
@robinst Thanks for your work
