### ISSUE TITLE
Markdown delete line can't transform to <del>

### ISSUE THREAD

**Issue by JohnJyong** [commonmark/commonmark-java#207]
Steps to reproduce the problem (provide example Markdown if applicable):

```
~~this is delete line~~ 
```

Expected behavior:

```
<del>this is delete line</del>
```

Actual behavior:

```
<p>~~this is delete line~~ </p>
```

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/)

**Comment by robinst** [comment]
Strikethrough is not part of the CommonMark spec. Because of that, it has to be enabled via an extension. See the strikethrough section in the README: https://github.com/commonmark/commonmark-java#strikethrough

So like this:

```
List<Extension> extensions = Arrays.asList(StrikethroughExtension.create());
Parser parser = Parser.builder()
        .extensions(extensions)
        .build();
HtmlRenderer renderer = HtmlRenderer.builder()
        .extensions(extensions)
        .build();
```

Does that help?

**Comment by JohnJyong** [comment]
thanks for your help
