### ISSUE TITLE
Can't support mathematical formula 

### ISSUE THREAD

**Issue by JohnJyong** [commonmark/commonmark-java#208]
Steps to reproduce the problem (provide example Markdown if applicable):

```
$x+y=z$ or  $$x+y=z$$
```

Expected behavior:

```
such as <span class="katex-display"></span>
```

Actual behavior:

```
<p>$$x+y=z$$</p>
```

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/)

**Comment by JohnJyong** [comment]
the markdown to html should render like the pciture below
![image](https://user-images.githubusercontent.com/76649700/125244370-d57b8500-e321-11eb-8e22-ef199e349c43.png)

**Comment by robinst** [comment]
This is not a bug. Maths rendering is not part of CommonMark. So it's an additional extension that would be needed (depending on how it's done).

Note that if you're rendering it as HTML and can add some JS, you can already do it, see https://github.com/commonmark/commonmark-java/issues/194#issuecomment-737856598

(Also linking some general discussion about syntax here: https://talk.commonmark.org/t/mathjax-extension-for-latex-equations/698/8)

**Comment by crowlogic** [comment]
this shouldnt be hard to do with https://github.com/opencollab/jlatexmath

**Comment by 07akioni** [comment]
> This is not a bug. Maths rendering is not part of CommonMark. So it's an additional extension that would be needed (depending on how it's done).
> 
> Note that if you're rendering it as HTML and can add some JS, you can already do it, see [#194 (comment)](https://github.com/commonmark/commonmark-java/issues/194#issuecomment-737856598)
> 
> (Also linking some general discussion about syntax here: https://talk.commonmark.org/t/mathjax-extension-for-latex-equations/698/8)

Render math formula after markdown html is generated has lots of corner cases.

For example:
```
`$`$
```
`$`$
```
$`$`
```
$`$`
would have different effects.
