### ISSUE TITLE
SourceSpans not set on Link nodes produced by AutolinkExtension

### ISSUE THREAD

**Issue by roman-r-m** [commonmark/commonmark-java#209]
Steps to reproduce the problem (provide example Markdown if applicable):

```
some text http://www.github.com and more text
```

Expected behavior:

When the parser is created with `.includeSourceSpans(IncludeSourceSpans.BLOCKS_AND_INLINES)` I'd expect all nodes to have source spans. In the above example, only the Paragraph node does.

**Comment by robinst** [comment]
Yep, the autolink extension currently doesn't handle source positions correctly, that's a bug.

The fix needs to be made somewhere here, along with tests: https://github.com/commonmark/commonmark-java/blob/main/commonmark-ext-autolink/src/main/java/org/commonmark/ext/autolink/internal/AutolinkPostProcessor.java#L34

I'll try to get a fix included in the next release.

**Comment by robinst** [comment]
Prepared a fix in PR https://github.com/commonmark/commonmark-java/pull/270

**Comment by robinst** [comment]
Fix released in 0.20.0: https://github.com/commonmark/commonmark-java/blob/main/CHANGELOG.md#0200---2022-10-20
