### ISSUE TITLE
Issue inline parser of Chinese

### ISSUE THREAD

**Issue by Naccl** [commonmark/commonmark-java#248]
When I parse like `**Foo:**Bar`, the result I want is `<strong>Foo:</strong>Bar`, but it rendered `**Foo:**Bar`. Just like before.

I think it is correct under the CommonMark specifications of English. But in Chinese, like `**标题：**这是一个例子`, We'd prefer it rendered `<strong>标题：</strong>这是一个例子`.  Instead of adding a whitespace between `**` and `这是` (It's all I can do right now), Because we use `：` rather than `:` . In fact, that's what most people does.

I wonder if an option can be added to select whether to turn on this "strict verification mode". I don't seem to see a similar issue.

Like this, in [InlineParserImpl.java#L538](https://github.com/commonmark/commonmark-java/blob/a3d392b03f8ca387d1647fb9fcdcf9932048bfd5/commonmark/src/main/java/org/commonmark/internal/InlineParserImpl.java#L538), when I always keep `canClose=true`, that will give me what I need.

<img width="1056" alt="image-20211219120230986" src="https://user-images.githubusercontent.com/44741777/146664616-d63b732a-3eba-413c-8be1-b75279ad62a5.png">

I don't know much about CommonMark, if I am wrong, please correct me, thank you! 😄

**Comment by boyshell** [comment]
您好！邮件已收到。

**Comment by robinst** [comment]
Hey! You can play around with the reference implementation here: https://spec.commonmark.org/dingus/

It behaves the same way that commonmark-java does for this.

Is there a good reason to include the `：` in the emphasis? Because this works as expected: `**标题**：这是一个例子`

**Comment by Naccl** [comment]
Yes, it can work well `**标题**：这是一个例子` , I dont have a good reason, but in Chinese custom, I've seen a lot of people write this `**标题：**`.

In other parser such as [marked](https://marked.js.org/demo/), it can give us what we want. I also know that this is because they are not strictly stick to the CommonMark specification.

So my suggestion that

> I wonder if an option can be added to select whether to turn on this "strict verification mode".

if possible.

Off topic, I think this is a suggestion with reference value, https://github.com/markedjs/marked/discussions/1202#discussioncomment-168114

**Comment by robinst** [comment]
Ok. We don't want to deviate from the spec on this, so we're not going to change parsing logic in commonmark-java.

You can try raising an issue against the spec here, but I have the feeling in order to make it work other common cases would break: https://github.com/commonmark/commonmark-spec

**Comment by Naccl** [comment]
After all, it's CommonMark, and I fully understand that.
Anyway, I still love this project, thank you for what you do!
