### ISSUE TITLE
Can commonmark support math formular?I didn’t find this feature, but it’s important, isn’t it?

### ISSUE THREAD

**Issue by jquanC** [commonmark/commonmark-java#249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include source code if possible.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by robinst** [comment]
Hey! That was asked before, see here: https://github.com/commonmark/commonmark-java/issues/208#issuecomment-882301168

The answer is still the same, it's not part of the spec but could be added as an extension. I don't plan to work on that in the near future, and I'm not sure what would be involved (as I mentioned in above link, it can already be done client-side I think). But if someone implements it as a third-party extension, I'd be happy to link it from this repo.

**Comment by jquanC** [comment]
Thanks for your reply!
I saw it, that helps a lot.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "commonmark/commonmark-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [commonmark/commonmark-java] Can commonmark support math formular?I didn’t find this feature, but it’s important, isn’t it? (Issue #249)





 
Hey! That was asked before, see here: #208 (comment)
 
The answer is still the same, it's not part of the spec but could be added as an extension. I don't plan to work on that in the near future, and I'm not sure what would be involved (as I mentioned in above link, it can already be done client-side I think). But if someone implements it as a third-party extension, I'd be happy to link it from this repo.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
