### ISSUE TITLE
Horizontal Rule ('---') render issue

### ISSUE THREAD

**Issue by Niloufar-Vafaei** [commonmark/commonmark-java#252]
Steps to reproduce the problem (provide example Markdown if applicable):
I using HtmlRenderer for renderer my html body . my HTML body-> "test\n---". when I pas this boy to render function, "---" are ignored and I don't know why. If I added more "\n" to my HTML body, the render fun can recognize "---" is "hr" tag.

**Comment by robinst** [comment]
Hey! So this:

```
test
---
```

Should render as a header (called "setext" headings in the [specification](https://spec.commonmark.org/0.30/#setext-headings)):

```
<h2>test</h2>
```

Whereas for a `hr`, you need an extra blank line:

```
test

---
```

Does that help?
