### ISSUE TITLE
Please create a .jar file, including your license, for distribution

### ISSUE THREAD

**Issue by JoePfeiffer** [commonmark/commonmark-java#253]
**Is your feature request related to a problem? Please describe.**
OpenRocket (https://github.com/openrocket/openrocket) has begun using your library, and we would like to properly cite your license.  At the moment we're just linking to the license here on your project page; we'd also like to link to a copy embedded in your .jar

**Describe the solution you'd like**
As in the title:  we'd very much appreciate if you could distribute a .jar with your license file, preferably at the top level.

**Describe alternatives you've considered**
We spent a little while trying to add it in ourselves, but eventually concluded simply having your library distributed with this would be of benefit both to us and to your other users.

**Additional context**
Add any other context about the feature request here.

**Comment by robinst** [comment]
> OpenRocket (https://github.com/openrocket/openrocket) has begun using your library

Cool project!

Yeah I agree that would be nice, just need to figure out the correct maven magic to do that. Help would be appreciated.

**Comment by robinst** [comment]
See PR: https://github.com/commonmark/commonmark-java/issues/253

**Comment by robinst** [comment]
Ok, released 0.18.2 with the fix for this: https://github.com/commonmark/commonmark-java/blob/main/CHANGELOG.md#0182---2022-02-24

It should show up on Maven Central shortly.

**Comment by JoePfeiffer** [comment]
Thank you!
