### ISSUE TITLE
 Customize field conversion

### ISSUE THREAD

**Issue by JohnJyong** [commonmark/commonmark-java#258]
**Is your feature request related to a problem? Please describe.**
I want to set some markdown fields not to be translated into html
ex：if I exclude the h1 label， ``` # test ```  will not be translated to ```<h1>test<h1>```  but  ``` <p># test<p>``` 

**Describe the solution you'd like**
we can add a field like 'includedLabelList' in the class HtmlRenderer, check the label list when doing the html rendering.

**Comment by robinst** [comment]
Hm, have you tried using `enabledBlockTypes` on the `Parser.Builder`?: https://www.javadoc.io/static/org.commonmark/commonmark/0.18.2/org/commonmark/parser/Parser.Builder.html#enabledBlockTypes-java.util.Set-

Try supplying every block type except `Heading.class`.

**Comment by JohnJyong** [comment]
I have tried the `enabledBlockTypes ` ,  However, it can't pinpoint a specific block，such as `Heading `
Includes `h1 h2 h3`... `ListBlock` includes `ol ul`

**Comment by JohnJyong** [comment]
> Hm, have you tried using `enabledBlockTypes` on the `Parser.Builder`?: https://www.javadoc.io/static/org.commonmark/commonmark/0.18.2/org/commonmark/parser/Parser.Builder.html#enabledBlockTypes-java.util.Set-
> 
> Try supplying every block type except `Heading.class`.

I have tried the `enabledBlockTypes ` ,  However, it can't pinpoint a specific block，such as `Heading `
Includes `h1 h2 h3`... `ListBlock` includes `ol ul`. 
 When I tried to pass the subset of them , the code below 
```
        Parser parser = Parser.builder()
                .extensions(extensions)
                .enabledBlockTypes(new HashSet<>(Arrays.asList(BlockQuote.class, OrderedList.class)))
                .build();
```

it will cause the nullPoint exception below
```
Exception in thread "main" java.lang.NullPointerException
	at org.commonmark.internal.DocumentParser.findBlockStart(DocumentParser.java:438)
	at org.commonmark.internal.DocumentParser.parseLine(DocumentParser.java:230)
	at org.commonmark.internal.DocumentParser.parse(DocumentParser.java:109)
	at org.commonmark.parser.Parser.parse(Parser.java:70)
```

Is my usage wrong? pls help , thanks in advance @robinst

**Comment by JohnJyong** [comment]
> Hm, have you tried using `enabledBlockTypes` on the `Parser.Builder`?: https://www.javadoc.io/static/org.commonmark/commonmark/0.18.2/org/commonmark/parser/Parser.Builder.html#enabledBlockTypes-java.util.Set-
> 
> Try supplying every block type except `Heading.class`.

May the `enabledBlockTypes` support ` image` and `link` blocks?

**Comment by robinst** [comment]
@JohnJyong the problem was that you specified `OrderedList`, which can't be individually enabled at the moment (only all `ListBlock` types or none). This works:

```
    @Test
    public void testDisableHeadings() {
        Parser parser = Parser.builder()
                .enabledBlockTypes(new HashSet<>(Arrays.asList(BlockQuote.class, ListBlock.class)))
                .build();
        HtmlRenderer renderer = HtmlRenderer.builder().build();

        Node doc = parser.parse("# test");
        String rendered = renderer.render(doc);

        assertEquals("<p># test</p>\n", rendered);
    }
```

It would be good if `enabledBlockTypes` checked the arguments and throw there, instead of NPEing later, but it doesn't currently do that.

> May the `enabledBlockTypes` support `image` and `link` blocks?

Those are not blocks, they're "inlines", as in within a paragraph, and they can't currently be disabled.

**Comment by JohnJyong** [comment]
Thank you very much for your help，I will try to solve these problems in my code logic
