### ISSUE TITLE
关于扩展语法问题

### ISSUE THREAD

**Issue by ifeisier** [commonmark/commonmark-java#259]
我扩展了两个语法：

```
[tabs]

#### **English**

Hello!

#### **French**

Bonjour!

#### **Italian**

Ciao!

[/tabs]
```

和 

```
[btn url="mailto:yuyesq@gmail.com" color="btn-danger"] 按钮扩展完成 [/btn]
```

单独使用这两个语法可以被正确解析，但是混合使用:

```
[tabs]

#### **English**

Hello!

#### **French**

Bonjour!

#### **Italian**

[btn url="mailto:yuyesq@gmail.com" color="btn-danger"] 按钮扩展完成 [/btn]

[/tabs]
```

`Italian` 中的 btn 无法被解析。

我应该怎么做，使 btn 解析。

================================

I've extended two grammars：

```
[tabs]

#### **English**

Hello!

#### **French**

Bonjour!

#### **Italian**

Ciao!

[/tabs]
```

and

```
[btn url="mailto:yuyesq@gmail.com" color="btn-danger"] 按钮扩展完成 [/btn]
```

These two grammars will be correctly parsed individually, but mixed:

```
[tabs]

#### **English**

Hello!

#### **French**

Bonjour!

#### **Italian**

[btn url="mailto:yuyesq@gmail.com" color="btn-danger"] 按钮扩展完成 [/btn]

[/tabs]
```

btn in 'Italian' cannot be resolved.

What should I do to make btn parse。

Don't laugh, this is my English translation。

**Comment by robinst** [comment]
Hi. I'm not sure what you mean. The `[btn ...` syntax is not anything provided by this library. It would be good to see the code to be able to reproduce this, a minimal example would be good. I can reopen if it is indeed related to commonmark-java.
