### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot add two delimiter processors for char '~' and minimum length 1

### ISSUE THREAD

**Issue by lpellegr** [commonmark/commonmark-java#271]
Using version 0.20.0 of commonmark-java with strikethrough extension leads to this exception at runtime:

> Caused by: java.lang.IllegalArgumentException: Cannot add two delimiter processors for char '~' and minimum length 1
> 	at org.commonmark.internal.StaggeredDelimiterProcessor.add(StaggeredDelimiterProcessor.java:54) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.internal.InlineParserImpl.addDelimiterProcessors(InlineParserImpl.java:92) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.internal.InlineParserImpl.calculateDelimiterProcessors(InlineParserImpl.java:69) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.internal.InlineParserImpl.<init>(InlineParserImpl.java:39) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.parser.Parser$Builder$1.create(Parser.java:272) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.parser.Parser.<init>(Parser.java:45) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.parser.Parser.<init>(Parser.java:28) ~[commonmark-0.20.0.jar:na]
> 	at org.commonmark.parser.Parser$Builder.build(Parser.java:128) ~[commonmark-0.20.0.jar:na]
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.23.jar:5.3.23]
> 	... 47 common frames omitted

Gradle dependencies used are:

> implementation 'org.commonmark:commonmark:0.20.0'
> implementation 'org.commonmark:commonmark-ext-autolink:0.20.0'
> implementation 'org.commonmark:commonmark-ext-gfm-tables:0.20.0'
> implementation 'org.commonmark:commonmark-ext-gfm-strikethrough:0.20.0'
> implementation 'org.commonmark:commonmark-ext-heading-anchor:0.20.0'
> implementation 'org.commonmark:commonmark-ext-image-attributes:0.20.0'

The renderer is initialized as follows:

```java
final List<Extension> extensions =
    Arrays.asList(
        AutolinkExtension.create(),
        HeadingAnchorExtension.create(),
        ImageAttributesExtension.create(),
        UnderlineExtension.create(),
        StrikethroughExtension.create(),
        SubscriptExtension.create(),
        SupscriptExtension.create(),
        TablesExtension.create());

this.markdownParser =
    Parser.builder().extensions(extensions).build();
this.markdownHtmlRenderer =
    HtmlRenderer.builder()
        .escapeHtml(true)
        .extensions(extensions)
        .nodeRendererFactory(VideoEmbedNodeRenderer::new)
        .sanitizeUrls(true)
        .build();
this.markdownPlaintextRenderer = TextContentRenderer.builder().extensions(extensions).stripNewlines(true).build();
```

Removing `StrikethroughExtension.create()` from the list of extensions or downgrading to version 0.19.0 fixes the issue.

**Comment by robinst** [comment]
Oh no. What's the input markdown? Just the section with tildes (`~`) should be enough.

**Comment by lpellegr** [comment]
It seems the issue is at runtime when the renderer initializes. No need to invoke the renderer.

**Comment by robinst** [comment]
Right, sorry (I hadn't looked at the stack trace because I was on mobile).

So I guess another extension also registers a delimiter processor for `~`, probably the subscript one?

So in 0.20.0 we adjusted the strikethrough extension to also handle single tildes, same as GitHub. So that is now a genuine conflict of syntaxes.

For that case we should probably add an option to configure the strikethrough extension to require double tildes, so that there's no conflict. What do you think?

**Comment by lpellegr** [comment]
Thanks for your answer. I confirm the issue is caused by the conflict with the SubscriptExtension which shares the same delimiter.

> For that case we should probably add an option to configure the strikethrough extension to require double tildes, so that there's no conflict. What do you think?

This would be really appreciated!

**Comment by robinst** [comment]
Prepared a fix in https://github.com/commonmark/commonmark-java/pull/272

It also improves the documentation and the error message mentions which delimiter processors conflict, which would have helped too for this.
