### ISSUE TITLE
TextContentRenderer renders broken tables

### ISSUE THREAD

**Issue by Boiarshinov** [commonmark/commonmark-java#281]
Steps to reproduce the problem:
1. Take any markdown table.
```md
| column |
| --- |
| value |
```

2. Parse it and render with `TextContentRenderer` back to markdown.

Expected behavior:
```md
| column |
| --- |
| value |
```

Actual behavior:
```md
column
value
```

As you can see the delimiter row is missing.

I have prepared the testcase to reproduce the problem in this PR: https://github.com/commonmark/commonmark-java/pull/280

**Comment by Boiarshinov** [comment]
I want to propose my PR based on studying of [GFM standard](https://github.github.com/gfm/#tables-extension-) mentioned in `TableExtension` class javadoc. Here is a description of a tables from there:
> A table is an arrangement of data with rows and columns, consisting of a single header row, a delimiter row separating the header from the data, and zero or more data rows.
> Each row consists of cells containing arbitrary text, in which inlines are parsed, separated by pipes (|). A leading and trailing pipe is also recommended for clarity of reading, and if there’s otherwise parsing ambiguity. Spaces between pipes and cell content are trimmed. Block-level elements cannot be inserted in a table.
> The delimiter row consists of cells whose only content are hyphens (-), and optionally, a leading or trailing colon (:), or both, to indicate left, right, or center alignment respectively. 

Delimiter row is obligatory. Least possible count of hyphens is not pointed, but all examples have at least three hyphens. I propose to render three hyphens everytime.
Futhermore we need to add colon to indicate alignment.

Also I want to propose some additional changes for table rendering based on GFM standard recommendations. 
1. Add leading and trailing pipe.
For now there is only pipes between columns.
Now:
```md
column| column
---| ---
```

Propose:
```md
| column| column|
| ---| ---|
```

2. Add spaces between pipes and column content. Now we have only one space between content and left pipe.
Now:
```md
| column| column|
| ---| ---|
```

Propose:
```md
| column | column |
| --- | --- |
```

These additional changes will not broke backward compatibility for anyone, because table rendering to markdown never worked correctly.

**Comment by Boiarshinov** [comment]
Here is my PR: https://github.com/commonmark/commonmark-java/pull/282

**Comment by robinst** [comment]
Hmm I think you misunderstood what `TextContentRenderer` is used for. It's not for rendering back to Markdown, it's for rendering to a simpler plain text with some of the formatting removed. Round-tripping was never a goal with `TextContentRenderer`. You might notice other things being rendered in a weird way with it, such as links.

**Comment by Boiarshinov** [comment]
My bad :)
I found discussion https://github.com/commonmark/commonmark-java/issues/12 and read it not too attentively. I saw you mentioning `TextContentRenderer` and thougth that it is for rendering java model back to markdown. I should have read your comment more closely
