### ISSUE TITLE
How to replace json code tag with <ac:structured-macro ..> tag

### ISSUE THREAD

**Issue by abhikt48** [commonmark/commonmark-java#283]
Generated JSON code tag is not represented as code or JSON code on the Confluence page. I need to convert `<code ..>..</code>` with confluence JSON macro. I can try to do with string manipulation which could be a bad/last idea to solve this issue.

Could you please suggest any approach at the library level which could solve this issue to replace `<code>` with `<ac:structured-macro>` tag? 

Please find the below input.

**Markdown**

![image](https://user-images.githubusercontent.com/22897837/207691859-e730461e-3816-416b-b13e-e9d1045115ad.png)

**Converted HTML**

```
<h1>Test1</h1>
<pre><code class="language-json">{
  &quot;stockRegionId&quot;: &quot;COM&quot;,
  &quot;name&quot;: &quot;BCD&quot;
}
</code></pre>
<h1>Test2</h1>
<pre><code class="language-json">{
  &quot;Amazon&quot;: &quot;CASH&quot;
}
</code></pre>
```

**Confluence View**
![image](https://user-images.githubusercontent.com/22897837/207692063-a34e20b9-2f31-42cc-87d8-29e8dd22bf84.png)

**Expected HTML**
```
<h1>Test1</h1>
<pre>
	<ac:structured-macro ac:name="code">
		<ac:parameter ac:name="language">json</ac:parameter>
		<ac:plain-text-body><![CDATA[{
  &quot;stockRegionId&quot;: &quot;COM&quot;,
  &quot;name&quot;: &quot;BCD&quot;
}
]]></ac:plain-text-body>
	</ac:structured-macro>
</pre>
<h1>Test2</h1>
<pre>
	<ac:structured-macro ac:name="code">
		<ac:parameter ac:name="language">json</ac:parameter>
		<ac:plain-text-body><![CDATA[{
  &quot;Amazon&quot;: &quot;CASH&quot;
}
]]></ac:plain-text-body>
	</ac:structured-macro>
</pre>
```

**Expected Confluence View:**
![image](https://user-images.githubusercontent.com/22897837/207692765-87bd65b7-5595-4a40-8102-2c41391d16a4.png)

**Used Dependencies**
```
<dependency>
	<groupId>org.commonmark</groupId>
	<artifactId>commonmark</artifactId>
	<version>0.18.1</version>
</dependency>
<dependency>
	<groupId>org.commonmark</groupId>
	<artifactId>commonmark-ext-gfm-tables</artifactId>
	<version>0.18.1</version>
</dependency>
```

**Comment by robinst** [comment]
Sure, that should be possible by customizing HTML rendering as described in the README here: https://github.com/commonmark/commonmark-java#customize-html-rendering

You would need to override rendering for `FencedCodeBlock`.
