### ISSUE TITLE
Heading anchor extension doesn't do anything useful

### ISSUE THREAD

**Issue by drogatkin** [commonmark/commonmark-java#284]
First, your product works as expected, however a very useful feature is missed. If I add **Heading anchor** extension, then I expect an anchor like:
        `<a name="header text"><h...,` 
but instead of that it adds _attribute_ `id="header text"` in "h" tag. Could you modify the extension as I request?

**Comment by boyshell** [comment]
您好！邮件已收到。

**Comment by drogatkin** [comment]
Actually, it works with the current solution, so sorry for a false alarm.

Заслано с моего LG G8, может быть криво
