### ISSUE TITLE
Consistently makes element-android formatting of code blocks wrong

### ISSUE THREAD

**Issue by theIDinside** [commonmark/commonmark-java#287]
Steps to reproduce the problem (provide example Markdown if applicable):

```cpp
struct Foo {
  Foo();
  int a;
}
```

Expected behavior: 
The behavior should be identical to what you see in this window. However, it consistently is not. 

```
struct Foo {
  Foo();
  int a;
}
```

Actual behavior:

```
struct Foo {
Foo();
int a;
}
```

The reason why I've found this problem is because [element-android](https://github.com/vector-im/element-android) depends on this library - and on the android app the code blocks consistently (for everyone _should_ be formatted erroneously). It's a bit strange that more people have not noticed this (to me). For Python code for instance, it makes the code completely unintelligible.

Here's what the common mark spec outputs (which is what should be expected): [https://spec.commonmark.org/dingus/](https://spec.commonmark.org/dingus/?text=%23%23%20Try%20CommonMark%0A%0A%60%60%60cpp%0Astruct%20Foo%20%7B%0A%20%20Foo()%3B%0A%20%20int%20a%3B%0A%7D%0A%60%60%60)

I think I've identified where the problem is and will be submitting a PR.

**Comment by boyshell** [comment]
您好！邮件已收到。

**Comment by robinst** [comment]
Can you describe the problem better? Using this as input:

~~~
## Try CommonMark

```cpp
struct Foo {
  Foo();
  int a;
}
```
~~~

It renders as:

~~~
<h2>Try CommonMark</h2>
<pre><code class="language-cpp">struct Foo {
  Foo();
  int a;
}
</code></pre>
~~~

Which is consistent with what your Dingus link does.
