### ISSUE TITLE
Support Trac-Wiki-Syntax as extension

### ISSUE THREAD

**Issue by haumacher** [commonmark/commonmark-java#291]
## Problem
The commonmark-java parser is designed to be extensible and there are already some optional syntax extensions implemented. The syntax of the Trac wiki pages (https://trac.edgewall.org/wiki/WikiFormatting) is not really markdown but very similar. It seems to be feasible to implement the Trac wiki special syntax as extensions to the commonmark-java parser. 

## Solution 
I'd like to implement an extension module to commonmark-java that provides a `ParserExtension` which allows to accept the syntax of the Trac wiki pages. 

## Alternatives
Eclipse Mylyn also offers a parser for Trac wiki syntax, but I've got no good results using this library.

**Comment by haumacher** [comment]
I'd like to have some feedback, if such add-on has a chance to get integrated into the commonmark-java project - especially, if some minor changes to the existing source would be necessary.

**Comment by haumacher** [comment]
A starting point can be found here: https://github.com/haumacher/commonmark-java/tree/trac-extension/commonmark-ext-trac

**Comment by robinst** [comment]
Trac, haven't heard that name in a while :).

I don't think it's popular enough to add as an extension in the official repository (along with the maintenance effort required), but there's nothing stopping you from releasing a separate library that offers the extension. Last time I checked, Sonatype OSSRH was still the recommended way to do it, there's a guide here: https://central.sonatype.org/publish/publish-guide/

Let me know if you run into trouble with publishing, I know it can be tricky.
