### ISSUE TITLE
TextContentRenderer only return literal of FencedCodeBlock?

### ISSUE THREAD

**Issue by hpumengzhao** [commonmark/commonmark-java#297]
It seems that `TextContentRenderer.render(FencedCodeBlock)` only returns  the literal?

## Steps to reproduce the problem (provide example Markdown if applicable)
For the following function `test`
```java
  public String test(String sourceCode, String language) {
      FencedCodeBlock codeBlock = new FencedCodeBlock();
      codeBlock.setInfo(language);
      codeBlock.setLiteral(sourceCode);
      codeBlock.setFenceChar('`');
      codeBlock.setFenceLength(3);
      return TEXT_RENDERER.render(codeBlock);
  }
```
## Expected behavior
The test function should return a rendered format of markdown code block below?

\```language
sourceCode
\```

## Actual behavior

It only returns the sourceCode.

## Analysis

It seems the root cause is  the `public void visit(FencedCodeBlock fencedCodeBlock)` function in `CoreTextContentNodeRenderer`

```java
    @Override
    public void visit(FencedCodeBlock fencedCodeBlock) {
        if (context.stripNewlines()) {
            textContent.writeStripped(fencedCodeBlock.getLiteral());
            writeEndOfLineIfNeeded(fencedCodeBlock, null);
        } else {
            textContent.write(fencedCodeBlock.getLiteral());
        }
    }
```

**Comment by robinst** [comment]
TextContentRenderer is not meant to render Markdown, only a plain text representation of the input with minimal extra characters.

See #12 for rendering as Markdown.

**Comment by boyshell** [comment]
您好！邮件已收到。
