### ISSUE TITLE
Escaping HTML must be done wisely

### ISSUE THREAD

**Issue by Rtaglia** [commonmark/commonmark-java#300]
Hi,

I dot not understand why the html entity such as &amp;euro; is converted into the unicode character € during the html rendering ?

The string &amp;euro ; is already HTML ready but not the unicode character € in most Html encoding files, so please do not convert all Html entities.

Other point about the Html rendering, if the source text already contains correct and valid HTML tags from the W3C  such &lt;div /&gt;, do not convert them to &amp;lt;div&amp;gt;. Keep them intact in the rendering result. Respect the choice of the author to beautify the output with Html tags. BUT, if the source text contains invalid HTML tags  (not belonging to the HTML standard tags) such as < or > or &lt;MyTag /&gt;,  ... please convert to &amp;lt;MyTag&amp;gt; These tags are not for the beauty of the Htm rendering, it is the content to show.

Good job you made, congratulations to all.

Steps to reproduce the problem (provide example Markdown if applicable):

```
# This is *Sparta* in &euro; 
<hr />
Class<?> t = null;
if( t == null && t!= null )
        return null;
```

Expected behavior:

```
<h1>This is <em>Sparta</em> in &euro;</h1>
<p><hr />
Class&lt;?&gt; t = null;
if( t == null &amp;&amp; t!= null )
        return null;</p>
```

Actual behavior:

```
<h1>This is <em>Sparta</em> in €</h1>
<p>&lt;hr /&gt;
Class&lt;?&gt; t = null;
if( t == null &amp;&amp; t!= null )
        return null;</p>
```

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/)

**Comment by robinst** [comment]
Note that the actual behavior is this:

```
<h1>This is <em>Sparta</em> in €</h1>
<hr />
Class<?> t = null;
if( t == null && t!= null )
        return null;
```

This is consistent with the spec, see here: https://spec.commonmark.org/dingus/?text=%23%20This%20is%20*Sparta*%20in%20%26euro%3B%20%0A%3Chr%20%2F%3E%0AClass%3C%3F%3E%20t%20%3D%20null%3B%0Aif(%20t%20%3D%3D%20null%20%26%26%20t!%3D%20null%20)%0A%20%20%20%20%20%20%20%20return%20null%3B

If you click on AST, you will see why: From the `<hr />` onwards, the text is parsed as a HTML block.

If you only want `<hr />` to be parsed as a HTML block, there needs to be a blank line after it, like so:

```
# This is *Sparta* in &euro; 
<hr />

Class<?> t = null;
if( t == null && t!= null )
        return null;
```

That renders like this:

```
<h1>This is <em>Sparta</em> in €</h1>
<hr />
<p>Class&lt;?&gt; t = null;
if( t == null &amp;&amp; t!= null )
return null;</p>
```

`&euro;` getting replaced is also consistent with the spec, but maybe we could add an option to the HTML renderer to escape all non-ASCII characters. But IMO it's 2024 and you should really be able to set the encoding and everything will handle it correctly.
