### ISSUE TITLE
Img node title parsed is NULL

### ISSUE THREAD

**Issue by WinJackOne** [commonmark/commonmark-java#304]
Here is test code

```
import org.commonmark.node.AbstractVisitor;
import org.commonmark.node.Image;
import org.commonmark.node.Node;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

public class Test {
    public static void main(String[] args) {


        Parser parser = Parser.builder().build();
        Node document = parser.parse("![text](/url.png)");

    }
}
```

The node Image, it's title is null

<img width="488" alt="image" src="https://github.com/commonmark/commonmark-java/assets/102780679/7f1aa8c7-8822-4f69-bd53-6cfc84e6694c">

**Comment by abhishekbarman1772** [comment]
package com.example;
import org.commonmark.node.AbstractVisitor;
import org.commonmark.node.Image;
import org.commonmark.node.Node;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

public class Test {
    public static void main(String[] args) {


        StringBuilder docString = new StringBuilder();
        docString.append("![text]");

        docString.append("(");

        docString.append("/url.png");

        // empty space         
        docString.append(' ');

        // opening of title columns
        docString.append('"');

        docString.append("Tille_value_goes_here");

        // closing of title columns
        docString.append('"');

        docString.append(")");

        // all you have to do is to create a string like this 
        //![text](/url.png "Tille_value_goes_here")
        System.out.println(docString.toString());

        Parser parser = Parser.builder().build();
        Node document = parser.parse(docString.toString());
        
        System.out.println(document.getFirstChild().getFirstChild());

    }
}

**Comment by abhishekbarman1772** [comment]
I have used string builder in this for creating a dynamic way of appending the strings but in general you have to make a string like this      

 -->![text](/url.png "Tille_value_goes_here")

**Comment by robinst** [comment]
@WinJackOne Not sure what your issue is about, what do you expect to happen? @abhishekbarman1772 is correct, to get a title you need to use the syntax for the title as per the spec: https://spec.commonmark.org/0.31.2/#images
