### ISSUE TITLE
Support CommonMark 0.31.2 specs

### ISSUE THREAD

**Issue by rock3r** [commonmark/commonmark-java#305]
**Is your feature request related to a problem? Please describe.**
A new revision of the CommonMark spec was made available last month, 0.31.2. It looks like a [minor spec revision](https://spec.commonmark.org/0.31.2/changes.html), mostly concerning with updating links, but it does contain some tweaks.

**Describe the solution you'd like**
Fully support the new changes to the spec.

**Describe alternatives you've considered**
None available

**Additional context**
https://spec.commonmark.org/0.31.2/

**Comment by robinst** [comment]
Done here:
- https://github.com/commonmark/commonmark-java/pull/308

**Comment by rock3r** [comment]
Ace, thanks!

**Comment by robinst** [comment]
Released in 0.22.0 now: https://github.com/commonmark/commonmark-java/blob/commonmark-parent-0.22.0/CHANGELOG.md#0220---2024-03-15
