### ISSUE TITLE
LinkReferenceDefinition takes over sourceSpans from a block following it

### ISSUE THREAD

**Issue by obask** [commonmark/commonmark-java#315]
#### Steps to reproduce the problem (provide example Markdown if applicable):

Run this example with `IncludeSourceSpans.BLOCKS` https://spec.commonmark.org/0.31.2/#example-210
```java
import org.commonmark.node.Node;
import org.commonmark.parser.IncludeSourceSpans;
import org.commonmark.parser.Parser;

public class Main {
    public static void main(String[] args) {
        Parser parser = Parser.builder().includeSourceSpans(IncludeSourceSpans.BLOCKS).build();
        String input = "[foo]: /url\n\"title\" ok";
        Node node = parser.parse(input);
        System.out.println("LinkReferenceDefinition spans: " + node.getFirstChild().getSourceSpans());
        System.out.println("Paragraph(last child)   spans: " + node.getLastChild().getSourceSpans());
    }
}
```

#### Expected behavior:
It should assign source spans to blocks
```
LinkReferenceDefinition spans: []
Paragraph(last child)   spans: [SourceSpan{line=1, column=0, length=10}]
```

#### Actual behavior:
It only assigns source spans to a `LinkReferenceDefinition` which is not a block
```
LinkReferenceDefinition spans: [SourceSpan{line=0, column=0, length=11}, SourceSpan{line=1, column=0, length=10}]
Paragraph(last child)   spans: []
```

PS [unrelated] a top level `Document` should probably only contain `Block`s while `LinkReferenceDefinition` is a `Node`

**Comment by robinst** [comment]
Thanks! Raised a PR to fix this.

> PS [unrelated] a top level `Document` should probably only contain `Block`s while `LinkReferenceDefinition` is a `Node`

Link reference definitions are a bit of an odd one in the way they're parsed. But in the spec, they're listed under blocks: https://spec.commonmark.org/0.31.2/#link-reference-definitions

We should probably change them to `extends Block` instead of `extends Node`. Thoughts? I made the change and none of the tests break, but it's technically an API change.

**Comment by robinst** [comment]
> We should probably change them to `extends Block` instead of `extends Node`. Thoughts? I made the change and none of the tests break, but it's technically an API change.

Done in https://github.com/commonmark/commonmark-java/commit/3038d47b71affe081e4357fda3b779755c932552
