### ISSUE TITLE
HTML block tag make other style not working

### ISSUE THREAD

**Issue by 1748995976** [commonmark/commonmark-java#316]
That' all:
- html block tags , followed by other styles after a line break will make other styles to not take effect
- In the parse process of DocumentParser - > HtmlBlockParser in commonMark, the following text is classified into HtmlBlock.

for example: text `Bold` can not be bold style
```html
<h1>Title</h1>
hello**Bold**
```

Please help me, thanks!

**Comment by 1748995976** [comment]
> Hi,
> 
> This is how HTML blocks work according to the spec, see the reference implementation: https://spec.commonmark.org/dingus/?text=%3Ch1%3ETitle%3C%2Fh1%3E%0Ahello**Bold**
> 
> If you switch to AST mode on the right, you will see that it's all parsed as one `html_block` element:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE document SYSTEM "CommonMark.dtd">
> <document xmlns="http://commonmark.org/xml/1.0">
>   <html_block>&lt;h1&gt;Title&lt;/h1&gt;
> hello**Bold**</html_block>
> </document>
> ```
> 
> To get separate blocks, you need a blank line in between.

Thank you for your reply. But why `hello**Bold**` need to be parsed as one html_block element, it isn't between the start tag `<h1>` and the end tag `</h1>`

**Comment by robinst** [comment]
See [this part of the spec](https://spec.commonmark.org/0.31.2/#html-block), point 6:

> **Start condition:** line begins with the string `<` or `</` followed by one of the strings (case-insensitive) ..., `h1`, ..., followed by a space, a tab, the end of the line, the string `>`, or the string `/>`.
> **End condition:** line is followed by a [blank line](https://spec.commonmark.org/0.31.2/#blank-line).

So the HTML block continues until the next blank line (or end of document).
